# Generated by Django 4.1.6 on 2023-02-04 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
